### ISSUE TITLE
lapis_ore missing ?

### ISSUE THREAD

**Issue by ensonic** [Napiophelios/LapisLazuli#2]
minecraft has
21  Lapis Lazuli Ore (minecraft:lapis_ore)
22  Lapis Lazuli Block (minecraft:lapis_block

so the counterpart for 22 would be "lapis:lapis_block".
http://www.minecraftinfo.com/lapislazuliblock.htm

but for 21 I can't fine one:
http://www.minecraftinfo.com/lapislazuliore.htm

Did I miss it or could this be added?

**Comment by Napiophelios** [comment]
there is no lapis ore, its found like any other stone
in large deposits underground.

the mod uses the stratus ore generation
to create layers of lapis here and there.

**Comment by ensonic** [comment]
Thanks for the quick reply. Shouldn't I see the lapis ore in creative mode? The main reason I am asking is that I need to know how the node is called, since I have a patch for https://github.com/minetest-tools/mcimport/issues/8 that uses your mod.

**Comment by Napiophelios** [comment]
The "ore" would be the lapis block itself.

this mod is a fork, you might want to use the original lapis mod instead
its much lighter and more mc like
https://forum.minetest.net/viewtopic.php?f=9&t=11287

**Comment by ensonic** [comment]
Ok, going for https://github.com/LINUXFREEAK/minetest-lapis, would be nice to have both things covered by one mod though since one cannot use both and yours has nice new blocks too.

By the 'ore' block I meant a block that is stone with blue speckles.

**Comment by Napiophelios** [comment]
I know what you meant, this mod just doesn't have that. I intended this mod to be used with Master Gollum's Darkage mod and kinda tried to mimic its style. Instead of ores, there are just mass formations of various stone types throughout the map.

**Comment by ensonic** [comment]
FYI: we resurrected the original one at  https://github.com/minetest-mods/lapis.

**Comment by Napiophelios** [comment]
didn't know it had died :)
