### ISSUE TITLE
ModError: Failed to load...

### ISSUE THREAD

**Issue by go-jdiego** [Napiophelios/LapisLazuli#5]
/usr/share/games/minetest/builtin/game/register.lua:65: Name lapis:lapis_block does not follow naming conventions: "lapislazuli:" or ":" prefix required
stack traceback:
	[C]: in function 'error'
	/usr/share/games/minetest/builtin/game/register.lua:65: in function 'check_modname_prefix'
	/usr/share/games/minetest/builtin/game/register.lua:115: in function 'register_item'
	/usr/share/games/minetest/builtin/game/register.lua:208: in function 'register_node'
	/home/user/.minetest/mods/lapislazuli/init.lua:11: in main chunk

**Comment by 3raven** [comment]
I have the same problem.

**Comment by Napiophelios** [comment]
I can not reproduce these errors

just tested with the latest Minetest-5.4.1-win64
and get no errors.

check to make sure you have the 'mod.conf' file 
in the lapis mod's folder
